[common_env_data]
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps =
    Wire@2.0.0
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git
    https://github.com/Seeed-Studio/Seeed_GFX.git
    bblanchon/ArduinoJson@6.17.3

[env:esp32dev]
platform = espressif32@6.8.1
board = esp32dev
framework = ${common_env_data.framework}
upload_speed = ${common_env_data.upload_speed}
monitor_speed = ${common_env_data.monitor_speed}
lib_deps = ${common_env_data.lib_deps}
build_flags =
    ;-DBOARD_HAS_PSRAM
    ;-mfix-esp32-psram-cache-issue
    -DESP32_PLATFORM

[env:seeed_xiao_esp32s3]
lib_extra_dirs = ${PROJECT_DIR}
;platform = espressif32@6.5.0
platform = espressif32@6.8.1
board = seeed_xiao_esp32s3
framework = ${common_env_data.framework}
upload_speed = ${common_env_data.upload_speed}
monitor_speed = ${common_env_data.monitor_speed}
lib_deps = ${common_env_data.lib_deps}
build_flags =
    ;-DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    ;-DLILYGO_T5_EPD47_S3
    -DCORE_DEBUG_LEVEL=1
    -DESP32_S3_PLATFORM
    -DBOARD_SCREEN_COMBO=507
    -DUSE_XIAO_EPAPER_DISPLAY_BOARD_EE04
monitor_filters =
    default
    esp32_exception_decoder


[env:T5-ePaper-S3]
lib_extra_dirs = ${PROJECT_DIR}
platform = espressif32@6.5.0
board = T5-ePaper-S3
framework = ${common_env_data.framework}
upload_speed = ${common_env_data.upload_speed}
monitor_speed = ${common_env_data.monitor_speed}
lib_deps = ${common_env_data.lib_deps}
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLILYGO_T5_EPD47_S3
    -DCORE_DEBUG_LEVEL=0
    -DESP32_S3_PLATFORM
monitor_filters =
    default
    esp32_exception_decoder

[platformio]
boards_dir = boards
description = A simple ePaper display demo for ESP32-S3-based boards, such as the Seeed Studio XIAO ESP32S3 and the LilyGo T5 ePaper S3. The code demonstrates how to initialize the display, draw basic shapes, and display text. It also includes support for PSRAM and USB CDC for debugging purposes.



